name: CI Pipeline

on: [push, pull_request]

jobs:
  formatting-check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 app.py

  unit-test:
    needs: formatting-check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'
        
      - name: Install pytest
        run: pip install pytest

      - name: Run unit tests
        run: pytest app_test.py

  deploy:
    needs: unit-test
    if: success()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy application
        run: echo "Deployment step here"  # Replace with your deployment script